### PR TITLE
Secondstep

### PR DESCRIPTION
**Pull request by wyaming89**
pin progress

### CODE REVIEW

**Comment by wyaming89** [comment]
now I have a problem, how can I get the "% of DAI supply that is providing liquidity at UniSwap v2". 
I can't  use  "DAI supply / All token supply".

**Comment by greefea** [comment]
To get the amount of DAI that is providing liquidity, handle the Mint and Burn events on a DAI pair and call the getReserves() function on the DAI contract and determine which of the two reserve numbers is the DAI reserve (by checking on token0 or token1: if token0 is DAI, then reseve0 is the DAI reserve, otherwise, reserve1 is the DAI reserve). DAI reserve is the amount of DAI providing liquidity. On the daily entity, using it as numerator and dividing by total supply of DAI will give the % of DAI supply that is providing liquidity at UniSwap v2.

**Comment by wyaming89** [comment]
the code just can work

**Comment by greefea** [comment]
Let's merge this & move on to 3rd step

**Pull request merged**
